version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: matas123456
      MYSQL_DATABASE: jwt
      MYSQL_USER: root
      MYSQL_PASSWORD: matas123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: tempb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/jwt
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: matas123456
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
    container_name: tempf
    ports:
      - "5173:5173" 
    depends_on:
      - backend 

volumes:
  mysql_data:
